ASKI-VACACIONES/ASKI-VACACIONES/Controllers/EventosController.cs
using ASKI_VACACIONES.Models;
using ASKI_VACACIONES.ServiceReference1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASKI_VACACIONES.Controllers
{
    public class EventosController : Controller
    {
        // GET: Ccalendario
        public ViewResult Eventos()
        {
            if (Session["User"] != null)
            {
                var permisos = Session["Permisos"] as string[];
                ViewBag.crear_evento = ViewBag.visualizar_evento = false;
                foreach (var permiso in permisos)
                {
                    switch (permiso)
                    {

                        case "Crear evento":
                            ViewBag.crear_evento = true;
                            break;

                        case "Visualizar evento":
                            ViewBag.visualizar_evento = true;
                            break;


                        default:
                            break;
                    }
                }

                return View();
            }
            else
            {
                return View("Login");
            }
        }

        

    

        [HttpPost]
        public ActionResult Eventos(EventosModel calendario)
        {
            if (Session["User"] != null)
            {
                if (ModelState.IsValid)
                {
                    Service1Client client = new Service1Client();
                    client.addTipo_dia(calendario.descripcion);
                    List<string> fecha = splitCadenaID(calendario.Fecha);
                    calendario.Tipo_dia_id = client.getultimoid_tipodia();
                    int talento = int.Parse(Session["Talento_Humano"].ToString());

                    foreach (var item in fecha)
                    {
                        string fechas = getFecha(item);
                        client.addCalendario(talento,fechas, calendario.Tipo_dia_id);
                   
                    }
                   client.Close();
                }
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }
        }

        private List<string> splitCadenaID(string cadenaID)
        {
            List<string> cadena = new List<string>();
            cadenaID += ",";
            string valor = "";
            for (int i = 0; i < cadenaID.Length; i++)
            {
                if (cadenaID[i] == ',')
                {
                    cadena.Add(valor);
                    valor = "";
                }
                else
                {
                    if (cadenaID[i] != ' ')
                    {
                        valor += cadenaID[i];
                    }
                   
                }

            }
            return cadena;
        }

        private string getFecha(string fecha)
        {
            string fe = "";
            string dia = "", mes = "", year = "";
            int separador = 0, contYear = 0;
            for (int i = 0; i < fecha.Length; i++)
            {
                if (fecha[i] == '/')
                {
                    separador++;
                }
                else if (separador == 0)
                {
                    mes += fecha[i];
                }
                else if (separador == 1)
                {
                    dia += fecha[i];
                }
                else if (separador == 2 && contYear < 4)
                {
                    year += fecha[i];
                    contYear++;
                }
                else
                {
                    break;
                }

            }
            fe = year + "-" + mes + "-" + dia;
            return fe;
        }

        [HttpPost]
        public ActionResult JSonEvento()
        {
            string json = "";
            Service1Client client = new Service1Client();
            var query = client.get_eventos();
           
            if (query == null)
            {
                json += "{" + String.Format("\"descripcion\":\"{0}\",\"fecha\":\"{1}\"", "0", "Null") + "}";
                json = "{\"draw\": 1,\"recordsTotal\": 1,\"recordsFiltered\": 1,\"data\": [" + json + "]}";
                return Content(json);
            }
            for (int i = 0; i < query.Count(); i++)
            {
                var f = client.get_fecha_eventos(query.ElementAt(i));
                List<string> fechas = new List<string>();
                foreach (var item in f) {
                    fechas.Add(item);
                }
                string cadenaf = concatenar_fechas(fechas);
                if (!json.Equals("")) { json += ","; }
                json += "{" + String.Format("\"descripcion\":\"{0}\",\"fecha\":\"{1}\"", query.ElementAt(i), cadenaf) + "}";
            }

            json = "{\"draw\": 1,\"recordsTotal\": 1,\"recordsFiltered\": 1,\"data\": [" + json + "]}";
            return Content(json);
        }

        private string concatenar_fechas( List<string> fechas)
        {
            string fecha = "";
            foreach (var item in fechas)
            {
                fecha += getFecha(item) + " ";
            }
            return fecha;
        }

    }
}

ASKI-VACACIONES/ASKI-VACACIONES/Views/Eventos/Eventos.cshtml
@model ASKI_VACACIONES.Models.EventosModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <h1>
        Eventos

    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Calendario"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Eventos</li>
    </ol>
</section>
<!--Date-->
<link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
@*<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>*@
<script src="http://multidatespickr.sourceforge.net/jquery-ui.multidatespicker.js"></script>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                @using (Html.BeginForm())
                {

                    <div class="panel-body">
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"></h3>
                            </div><!-- /.box-header -->
                            <!-- form start -->
                            <form class="form-horizontal" id="formulario">

                                
                                <div class="box-body">
                                    <div class="form-group">
                                        <label for="inputdescripcion" class="col-sm-2 control-label">Eventos</label>
                                        <div class="col-sm-10">
                                            <p>@Html.TextBoxFor(x => x.descripcion, new { @class = "form-control", type = "text" })</p>

                                            
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="inputfecha" class="col-sm-2 control-label">Fecha</label>
                                        <div class="col-sm-10">
                                            <div class="input-group">
                                                <p>@Html.TextBoxFor(x => x.Fecha, new { @class = "form-control", type = "text", id = "datePick" })</p>

                                                @*<input id="datePick" type="text" />*@
                                                <div class="input-group-btn">
                                                    <button id="add-new-event" type="submit" class="btn btn-primary btn-flat">Crear</button>
                                                </div><!-- /btn-group -->
                                            </div>
                                        </div>
                                    </div>
                                     
                                


                                    </div>
                                <div class="form-group">
                                    <div class="box">
                                        <div class="box-header">
                                            <h3 class="box-title"></h3>
                                        </div><!-- /.box-header -->
                                        <div class="box-body">


                                            <table id="eventos" class="datatable table table-striped table-bordered" width="65%">
                                                <thead>
                                                    <tr>
                                                        <th>Eventos</th>
                                                        <th>Fecha</th>
                                                    </tr>
                                                </thead>

                                                <tfoot>
                                                    <tr>
                                                        <th>Eventos</th>
                                                        <th>Fecha</th>
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div><!-- /.box-body -->
                                    </div><!-- /.box -->
                                </div>

                            </form>
                        </div><!-- /.box -->
                    </div>

                }


            </div>

        </div>
    </div>

    <!-- Left col -->
    <section class="col-lg-7 connectedSortable"></section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
    <section class="col-lg-5 connectedSortable"></section><!-- right col -->


</section><!-- /.content -->

<script type="text/javascript">
    $(document).ready(function () {
        $('#datePick').multiDatesPicker();
    });

</script>

<script type="text/javascript">
    $(document).ready(function () {
        var table = $('#eventos').DataTable({
            responsive: true,
            "ajax": {
                "url": "@Url.Action("JSonEvento", "Eventos")",
            "type": "POST"
        },

             "columns": [
    
                    { "data": "descripcion" },
                    { "data": "fecha" }
    ],
        });
    });
</script>