ASKI-VACACIONES/ASKI-VACACIONES/Controllers/JerarquiaController.cs
using ASKI_VACACIONES.Models;
using ASKI_VACACIONES.ServiceReference1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASKI_VACACIONES.Controllers
{
    public class JerarquiaController : Controller
    {
        // GET: Jerarquia
        public ActionResult AddJefe()
        {
            if (Session["User"] != null)
            {
                Service1Client client = new Service1Client();
                var query = client.getTbl_usuarios();
                List<string> emple = new List<string>();
                foreach (var item in query)
	            {
		            emple.Add(item.primer_nombre + " " + item.primer_apellido + "|" + item.talento_humano);
	            }
                ViewBag.Empleados = emple;

                var quer = client.getTbl_departamentos();
                List<string> depto = new List<string>();
                foreach (var item in quer)
                {
                    depto.Add(item.descripcion+ "|" + item.departamentoid);
                }
                client.Close();
                ViewBag.Empleados = emple;
                ViewBag.Departamentos = depto;


                return View();
            }
                
            else
                return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public ActionResult AddJefe(JerarquiaModel model)
        {
            if (Session["User"] != null)
            {
                Service1Client client = new Service1Client();
                int deptoId = int.Parse(splitID(model.departamentoid.ToString()));
                int talentoH = int.Parse(splitID(model.talento_humano_jefe.ToString()));
                if(deptoId!=0&&talentoH!=00)
                {
                    client.deleteDepartamento_Jefe(deptoId);
                    client.addDepartamento_Jefe(talentoH, deptoId);
                }

                var query = client.getTbl_usuarios();
                var quer = client.getTbl_departamentos();
                client.Close();
                List<string> emple = new List<string>();
                foreach (var item in query)
                {
                    emple.Add(item.primer_nombre + " " + item.primer_apellido + "|" + item.talento_humano);
                }
                ViewBag.Empleados = emple;

                List<string> depto = new List<string>();
                foreach (var item in quer)
                {
                    depto.Add(item.descripcion + "|" + item.departamentoid);
                }
                ViewBag.Empleados = emple;
                ViewBag.Departamentos = depto;
                return View();
            }

            else
                return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public ActionResult getJefe_Departamanto()
        {

            string json = "";
            Service1Client client = new Service1Client();
            var depto = client.getTbl_departamentos();
            for (int i = 0; i < depto.Count(); i++)
            {
                if (!json.Equals("")) { json += ","; }
                int deptoid = depto.ElementAt(i).departamentoid;
                string jefe = client.getJefe_Departamento(deptoid);
                json += "{" + String.Format("\"departamento\":\"{0}\",\"nombre\":\"{1}\"", depto.ElementAt(i).descripcion, jefe) + "}";
            }

            json = "{\"draw\": 1,\"recordsTotal\": 1,\"recordsFiltered\": 1,\"data\": [" + json + "]}";
            return Content(json);
        }

       // [HttpPost]
        [HttpPost]
        public ActionResult getUsuarios_TalentoHumano()
        {
            string json = "";
            Service1Client client = new Service1Client();
            var query = client.getTbl_usuarios();
            if (query == null)
            {
                json += String.Format("\"{0}\"", "");
                json = "[" + json + "]";
                return Content(json);
            }
            for (int i = 0; i < query.Count(); i++)
            {
                if (!json.Equals("")) { json += ","; }
                string Usuario = query.ElementAt(i).primer_nombre + " " + query.ElementAt(i).primer_apellido + "|" + query.ElementAt(i).talento_humano;
                json += String.Format("\"{0}\"", Usuario);

           }

           json = "[" + json + "]";
            return Content(json);
        }

        private string splitID(string cadena)
        {
            string valor = "0";
            bool id = false;
            if (cadena == null)
                return valor;
            for (int i = 0; i < cadena.Length; i++)
            {
                if (cadena[i] == '|')
                {
                    id = true;
                    valor = "";
                }
                else if(id)
                {
                    valor += cadena[i];
                }

            }
            return valor;
        }

        public ActionResult EditarJefeEmpleado()
        {
            if (Session["User"] != null)
            {
                Service1Client client = new Service1Client();
                var query = client.getTbl_usuarios();
                List<string> emple = new List<string>();
                foreach (var item in query)
                {
                    emple.Add(item.primer_nombre + " " + item.primer_apellido + "|" + item.talento_humano);
                }
                ViewBag.Emple = emple;

                return View();
            }

            else
                return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public ActionResult EditarJefeEmpleado(JerarquiaModel model, string submitButton)
        {
            if (Session["User"] != null)
            {
                Service1Client client = new Service1Client();
                if (submitButton.Equals("Editar"))
                {
                    var query = client.getTbl_usuarios();
                    var hola = client.getUsuario(model.talento_humano);
                    UsuariosModel usuario = new UsuariosModel();
                    List<string> emple = new List<string>();
                    foreach (var item in query)
                    {
                        emple.Add(item.primer_nombre + " " + item.primer_apellido + "|" + item.talento_humano);
                    }
                    ViewBag.Emple = emple;
                    if (hola == null)
                    {
                        client.Close();
                        return View();
                    }
                    ViewBag.nombre = hola.primer_nombre;
                    ViewBag.apellido = hola.segundo_apellido;
                    ViewBag.nombre = ViewBag.primerombre + ViewBag.apellido;
                }

                client.Close();
                return View();

            }
            else
                return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public ActionResult getDptJefe()
        {

            string json = "";
            Service1Client client = new Service1Client();
            var query = client.getDepartamento_Usuario();
            for (int i = 0; i < query.ElementAt(0).Count(); i++)
            {
                if (!json.Equals("")) { json += ","; }
                int thEm=int.Parse(query.ElementAt(3).ElementAt(i));
                int depto = int.Parse(query.ElementAt(1).ElementAt(i));
                int talentoJefe = client.getTalentoHumano_Jefe(thEm,depto);
                var usu = client.getUsuario(talentoJefe);
                 string NombreJefe="";
                 if (usu == null)
                 {
                     NombreJefe = "Sin Asignar";
                     talentoJefe = 0;
                 }
                 else
                 {
                     NombreJefe = usu.primer_nombre + " " + usu.primer_apellido;
                 }
               // string jefe = client.getj
                json += "{" + String.Format("\"descripcion\":\"{0}\",\"departamentoid\":\"{1}\",\"nombre\":\"{2}\",\"talento_humano\":\"{3}\",\"nombreJefe\":\"{4}\",\"talentoJefe\":\"{5}\"", query.ElementAt(0).ElementAt(i), query.ElementAt(1).ElementAt(i), query.ElementAt(2).ElementAt(i), query.ElementAt(3).ElementAt(i),NombreJefe,talentoJefe) + "}";


            }

            json = "{\"draw\": 1,\"recordsTotal\": 1,\"recordsFiltered\": 1,\"data\": [" + json + "]}";
            return Content(json);
        }
    }
}

ASKI-VACACIONES/ASKI-VACACIONES/Controllers/SolicitudesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASKI_VACACIONES.ServiceReference1;
using ASKI_VACACIONES.Models;

namespace ASKI_VACACIONES.Controllers
{
    public class SolicitudesController : Controller
    {
        // GET: Solicitudes
        public ActionResult NuevaSolicitud() 
        {
            if (Session["User"] != null)
            {
                Service1Client client = new Service1Client();
                var query = client.getTbl_usuarios();
                client.Close();
                List<string> emple = new List<string>();
                foreach (var item in query)
                {
                    emple.Add(item.primer_nombre + " " + item.primer_apellido + "|" + item.talento_humano);
                }
                ViewBag.jefe = emple;

                
                return View();
            }

            else
                return RedirectToAction("Login", "Home");
        }
    [HttpPost]
        public ActionResult NuevaSolicitud(SolicitudesModel solicitudes)
        {

            if (Session["User"] != null)
            {
                Service1Client client = new Service1Client();
                if (ModelState.IsValid)
                {
                    
                    int talento = int.Parse(Session["Talento_Humano"].ToString()); 
       


                    if (client.approveRequest(solicitudes.Fechainicio, solicitudes.Fechafin) == true)
                    {
                        client.addVacacion(talento,solicitudes.Fechainicio, solicitudes.Fechafin, DateTime.Now.Date, DateTime.Now.Date, 1);
                    
                    }
                }
                var query = client.getTbl_usuarios();
                client.Close();
                List<string> emple = new List<string>();
                foreach (var item in query)
                {
                    emple.Add(item.primer_nombre + " " + item.primer_apellido + "|" + item.talento_humano);
                }
                ViewBag.jefe = emple;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Home");
            }

        }
        public ActionResult MisSolicitudes() 
        {
            if (Session["User"] != null)
                return View();
            else
                return RedirectToAction("Login", "Home");
        }

        private List<int> splitCadenaID(string cadenaID)
        {
            List<int> numero = new List<int>();
            string valor = "";
            for (int i = 0; i < cadenaID.Length; i++)
            {
                if (cadenaID[i] == '/')
                {
                    numero.Add(int.Parse(valor));
                    valor = "";
                }
                else
                {
                    valor += cadenaID[i];
                }

            }
            return numero;
        }

        public ActionResult Aprobar_solicitud() { return View(); }
        [HttpPost]
        public ActionResult getsolicitud()
        {

            string json = "";
            Service1Client client = new Service1Client();
            var query = client.getsolicitud_pendiente(int.Parse(Session["Talento_humano"].ToString()));
            for (int i = 0; i < query.ElementAt(0).Count(); i++)
            {
                if (!json.Equals("")) { json += ","; }
                
                // string jefe = client.getj
                json += "{" + String.Format("\"Nombre\":\"{0}\",\"fecha_salida\":\"{1}\",\"fecha_entrada\":\"{2}\",\"dias\":\"{3}\"", query.ElementAt(0).ElementAt(i), query.ElementAt(1).ElementAt(i), query.ElementAt(2).ElementAt(i), query.ElementAt(3).ElementAt(i)) + "}";


            }

            json = "{\"draw\": 1,\"recordsTotal\": 1,\"recordsFiltered\": 1,\"data\": [" + json + "]}";
            return Content(json);
        }
    }
}

ASKI-VACACIONES/ASKI-VACACIONES/Views/Solicitudes/Aprobar_solicitud.cshtml
@model ASKI_VACACIONES.Models.SolicitudesModel
@{
    ViewBag.Title = "Aprobar_solicitud";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <h1>
       Aprobacion de solicitud

    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Calendario"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Aprobacion</li>
    </ol>
</section>

<!-- Content Wrapper. Contains page content -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                @using (Html.BeginForm())
                {

                    <div class="panel-body">

                        <!-- form start -->
                        @Html.ValidationSummary(true)
                        <form class="form-horizontal">



                            <div class="box">
                                <div class="box-body">

                                    <div class="form-group">
                                        <table id="empleado_jefe" class="datatable table table-striped table-bordered" width="85%">

                                            <thead>
                                                <tr>
                                                    <th>Empleado</th>
                                                    <th>Fecha de Salida</th>
                                                    <th>Fecha entrada</th>
                                                    <th>Dias solicitados</th>
                                                    <th>Estado</th>
                                                </tr>
                                            </thead>
                                        </table>

                                    </div><!-- /.box-body -->
                                </div><!-- /.box -->
                                <!--Modal-->
                                <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true" onclick="recargar();"></span></button>
                                                <h4 class="modal-title custom_align" id="Heading"></h4>
                                            </div>
                                            <div class="modal-body">
                                                
                                                <div class="form-group">
                                                    

                                                </div>
                                                <div class="modal-footer ">

                                                    <button type="button" class="btn btn-primary btn-lg" style="width: 100%;"><span class="glyphicon glyphicon-ok-sign"></span> Actualizar</button>
                                                </div>
                                            </div>
                                            <!-- /.modal-content -->
                                        </div>
                                        <!-- /.modal-dialog -->
                                    </div>


                        </form>
                    </div>

                }
            </div>

        </div>
    </div>

    <!-- Left col -->
    <section class="col-lg-7 connectedSortable"></section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
    <section class="col-lg-5 connectedSortable"></section><!-- right col -->


</section><!-- /.content -->


<script type="text/javascript">



    $(document).ready(function () {
        var rows_selected = [];
        var table = $('#empleado_jefe').DataTable({
            responsive: true,
            "ajax": {
                "url": "@Url.Action("getDptJefe", "Jerarquia")",
                "type": "POST"
            },

            "columns": [
                { "data": "Nombre",},
                { "data": "fecha_salida" },
                { "data": "fecha_entrada" },
                { "data": "dias" },
                {
                        //"data": "id",
                        'className': 'dt-body-center',
                        'render': function (id) {
                            return '<p data-placement="top" data-toggle="tooltip" title="Editar jefe"><input type="button" name="submitButton" value="Editar" class="btn btn-primary pull-right"  data-title="Edit" onclick="openModal()"/></p>';

                 }
                }

            ],
            'order': [1, 'asc']

        });

    });

    function openModal()
    {
        $("#edit").modal('show');
    }

</script>

ASKI-VACACIONES/ASKI-VACACIONES/Views/Solicitudes/MisSolicitudes.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--Trying-->
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<style>
    .custom-combobox {
        position: relative;
        display: block;
    }

    .custom-combobox-toggle {
        position: absolute;
        top: 0;
        bottom: 0;
        margin-left: -1px;
        padding: 0;
    }

    .custom-combobox-input {
        margin: 0;
        padding: 5px 10px;
    }
</style>

<script>
    (function ($) {
        $.widget("custom.combobox", {
            _create: function () {
                this.wrapper = $("<span>")
                  .addClass("custom-combobox")
                  .insertAfter(this.element);

                this.element.hide();
                this._createAutocomplete();
                this._createShowAllButton();
            },

            _createAutocomplete: function () {
                var selected = this.element.children(":selected"),
                  value = selected.val() ? selected.text() : "";

                this.input = $("<input>")
                  .appendTo(this.wrapper)
                  .val(value)
                  .attr("title", "")
                  .addClass("custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left form-control")
                  .autocomplete({
                      delay: 0,
                      minLength: 0,
                      source: $.proxy(this, "_source")
                  })
                  .tooltip({
                      tooltipClass: "ui-state-highlight"
                  });

                this._on(this.input, {
                    autocompleteselect: function (event, ui) {
                        ui.item.option.selected = true;
                        this._trigger("select", event, {
                            item: ui.item.option
                        });
                    },

                    autocompletechange: "_removeIfInvalid"
                });
            },

            _createShowAllButton: function () {
                var input = this.input,
                  wasOpen = false;

                $("<a>")
                  .attr("tabIndex", -1)
                  .attr("title", "Show All Items")
                  .tooltip()
                  .appendTo(this.wrapper)
                  .button({
                      icons: {
                          primary: "ui-icon-triangle-1-s"
                      },
                      text: false
                  })
                  .removeClass("ui-corner-all")
                  .addClass("custom-combobox-toggle ui-corner-right")
                  .mousedown(function () {
                      wasOpen = input.autocomplete("widget").is(":visible");
                  })
                  .click(function () {
                      input.focus();

                      // Close if already visible
                      if (wasOpen) {
                          return;
                      }

                      // Pass empty string as value to search for, displaying all results
                      input.autocomplete("search", "");
                  });
            },

            _source: function (request, response) {
                var matcher = new RegExp($.ui.autocomplete.escapeRegex(request.term), "i");
                response(this.element.children("option").map(function () {
                    var text = $(this).text();
                    if (this.value && (!request.term || matcher.test(text)))
                        return {
                            label: text,
                            value: text,
                            option: this
                        };
                }));
            },

            _removeIfInvalid: function (event, ui) {

                // Selected an item, nothing to do
                if (ui.item) {
                    return;
                }

                // Search for a match (case-insensitive)
                var value = this.input.val(),
                  valueLowerCase = value.toLowerCase(),
                  valid = false;
                this.element.children("option").each(function () {
                    if ($(this).text().toLowerCase() === valueLowerCase) {
                        this.selected = valid = true;
                        return false;
                    }
                });

                // Found a match, nothing to do
                if (valid) {
                    return;
                }

                // Remove invalid value
                this.input
                  .val("")
                  .attr("title", value + " didn't match any item")
                  .tooltip("open");
                this.element.val("");
                this._delay(function () {
                    this.input.tooltip("close").attr("title", "");
                }, 2500);
                this.input.autocomplete("instance").term = "";
            },

            _destroy: function () {
                this.wrapper.remove();
                this.element.show();
            }
        });
    })(jQuery);

    $(function () {
        $("#combobox").combobox();
        $("#toggle").click(function () {
            $("#combobox").toggle();
        });
    });
</script>
<section class="content-header">
    <h1>
        Mis solicitudes

    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Calendario"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Mis solicitudes</li>
    </ol>
</section>



<!-- Content Wrapper. Contains page content -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"></h3>
                            </div><!-- /.box-header -->
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Inicio de vacaciones</th>
                                        <th>Fin de vacacioens</th>
                                        <th>Dias a disfrutar</th>
                                        <th>Responsable</th>
                                        <th>Estado</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>12/03/14</td>
                                        <td>18/03/14</td>
                                        <td>7</td>
                                        <td>Carlos Hernandez</td>
                                        <td>Aprobado</td>
                                    </tr>
                                    <tr>
                                        <td>12/03/15</td>
                                        <td>18/03/15</td>
                                        <td>7</td>
                                        <td>Carlos Hernandez</td>
                                        <td>Pediente</td>
                                    </tr>
                                   
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Inicio de vacaciones</th>
                                        <th>Fin de vacacioens</th>
                                        <th>Dias a disfrutar</th>
                                        <th>Responsable</th>
                                        <th>Estado</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div><!-- /.box -->
                    </div>
            </div>

        </div>
    </div>

    <!-- Left col -->
    <section class="col-lg-7 connectedSortable"></section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
    <section class="col-lg-5 connectedSortable"></section><!-- right col -->


</section><!-- /.content -->

ASKI-VACACIONES/ASKI-VACACIONES/Views/Solicitudes/NuevaSolicitud.cshtml
@model ASKI_VACACIONES.Models.SolicitudesModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <h1>
        Nueva solicitud

    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Calendario"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Nueva solicitud</li>
    </ol>
</section>
<!-- Content Wrapper. Contains page content -->
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
              @using (Html.BeginForm()) {

                   <div class="panel-body">
                        <div class="box box-primary">
                            <div class="box-header with-border">
                                <h3 class="box-title"></h3>
                            </div><!-- /.box-header -->
                            <!-- form start -->
                            <form class="form-horizontal" id="formulario">
                                  
                                <div class="form-group">
                                    <label for="inputjefe" class="col-sm-2 control-label">Jefe inmediato</label>
                                    <div class="col-sm-10">
                                        <div class="ui-widget">
                                            <p>
                                                <select id="combobox" class="form-control">
                                                    <option value=""></option>
                                                    @foreach (var item in @ViewBag.jefe)
                                                    {
                                                        <option value="@item">@item</option>
                                                    }

                                                </select>
                                            </p>
                                        </div>


                                    </div>
                                </div>


                                        <div class="form-group">
                                            <label for="inputfecha" class="col-sm-2 control-label">Inicio de vacaciones</label>
                                            <div class="col-sm-10">
                                                <p>@Html.TextBoxFor(x => x.Fechainicio, new { @class = "form-control", type = "date" })</p>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="inputfecha" class="col-sm-2 control-label">Fin de vacaciones</label>
                                            <div class="col-sm-10">
                                                <p>@Html.TextBoxFor(x => x.Fechafin, new { @class = "form-control", type = "date" })</p>
                                            </div>
                                        </div>
                                         
                                        <div class="box-footer">
                                            <button type="submit" class="btn btn-info pull-right">Solicitar</button>
                                         </div><!-- /.box-footer -->
                            </form>
                        </div><!-- /.box -->
                    </div>

                
}

            </div>

        </div>
    </div>

    <!-- Left col -->
    <section class="col-lg-7 connectedSortable"></section><!-- /.Left col -->
    <!-- right col (We are only adding the ID to make the widgets sortable)-->
    <section class="col-lg-5 connectedSortable"></section><!-- right col -->


</section><!-- /.content -->